### ISSUE TITLE
Implementacja nowego kodowania w Pythonie

### ISSUE THREAD

**Issue by vis256** [MagisterkaOsu/osu#4]
Przykładowy y: `00000000000000000000010101010101` 

Przykładowa maska - `110011`

Przykładowe wejście - `1001`

x:`00000000000000000000000000000001` - czy jest kodowana informacja

0 na ostatnim bicie - nie ma kodowania w tej ramce; 1 na ostatnim bicie - jest kodowanie

y:`00000000000000000000010101100101` - jeśli jest kodowana informacja to:

zakodowanie kolejnych bitów wejścia na pozycjach maski, których bit jest równy 1

**Comment by Helga151** [comment]
[https://github.com/MagisterkaOsu/replay-editor/commit/7a4cbb58351ce2b8952908455cd5b9ed9a3f0b46](url)
